### PR TITLE
Close connection & handle EOF

### PR DESCRIPTION
**Pull request by mitchellwrosen**

### CODE REVIEW

**Comment by mitchellwrosen** [comment]
Oops, didn't mean to add the stack.yaml resolver change. It builds against lts-6.14 fine, though. Let me know if I should revert.

**Comment by tfausak** [comment]
I'd prefer to keep the resolver on something that provides GHC 8. But otherwise, this looks great! Thank you! :fireworks:

**Comment by mitchellwrosen** [comment]
Updated

**Comment by tfausak** [comment]
Great, thanks! I'll release this as version 1.1.1.

**Pull request merged**
